import Link from 'next/link'

const support = process.env.NEXT_PUBLIC_SUPPORT_EMAIL

export default function TermsPage() {
  return <main className="min-h-screen bg-[#faf7f0] px-4 py-10 text-stone-900"><article className="mx-auto max-w-3xl rounded-3xl border border-stone-200 bg-white p-6 shadow-sm sm:p-9"><Link href="/" className="font-bold text-emerald-800">PyLearn Pro</Link><p className="mt-5 text-xs font-bold uppercase tracking-wider text-amber-800">Course terms</p><h1 className="mt-1 text-3xl font-extrabold">Terms of Use</h1><p className="mt-2 text-xs text-stone-500">Last updated: 8 October 2026</p>
    <section className="mt-7 space-y-5 text-sm leading-7 text-stone-700">
      <div><h2 className="font-bold text-stone-900">1. About the academy</h2><p>PyLearn Pro provides beginner-friendly programming lessons and browser-based practice. The current course is Python Foundations. The planned four-month pathway is still being prepared: Week 1 is published, later lessons are not yet available, and capstone and certificate features are not live. We do not promise a release date for unpublished material.</p></div>
      <div><h2 className="font-bold text-stone-900">2. Accounts and learner age</h2><p>Give accurate account details and keep your password private. Learners under 18 need a parent or legal guardian to review the Admission Document and confirm permission before lessons open. A learner must also read the Admission Document and confirm they have the listed materials.</p></div>
      <div><h2 className="font-bold text-stone-900">3. Lessons and progress</h2><p>The course is self-paced, with a suggested goal of five sessions of about 30 minutes each week. This is a learning suggestion, not an attendance rule. Lesson progress and quick-check results are saved to the account. Browser code practice is for learning and is not a trusted assignment grade. AI explanations may be inaccurate and should be checked against lesson material.</p></div>
      <div><h2 className="font-bold text-stone-900">4. Fees and payments</h2><p>Prices are set by the administrator and shown on the website and Payments page. KSh and USD display amounts may differ; M-Pesa charges use the displayed KSh price. Paid payment options remain disabled until the relevant paid lessons are published and available. When an option is enabled, learners pay by KCB Paybill 522522, account 1288171692, then submit the last four receipt characters and payer phone number. Never provide an M-Pesa PIN.</p><p className="mt-2">A request stays pending until an administrator checks the M-Pesa message and confirms it. Monthly access lasts 30 days from confirmation. If a payment cannot be matched or is declined, the learner may correct the details and submit again. A refund and cancellation policy has not yet been published; unclear or mistaken payments are referred to the administrator for review. Do not pay for a plan unless its payment option is enabled in PyLearn Pro.</p></div>
      <div><h2 className="font-bold text-stone-900">5. Optional AI assistance</h2><p>If a learner chooses AI help, the question and any code they send are processed by Google Gemini to create a response. Depending on the Google service tier, prompts and replies may be used to improve Google services and may be reviewed by humans. Do not submit passwords, personal details, or confidential information.</p></div>
      <div><h2 className="font-bold text-stone-900">6. Changes and support</h2><p>Published lessons, fees, and course information may change. A major Admission Document update requires affected learners and guardians to accept it again; a price-only change does not. For questions or payment problems, contact {support ? <a className="font-semibold text-emerald-800 underline" href={`mailto:${support}`}>{support}</a> : 'the school support contact, which will be published before paid enrollment opens'}.</p></div>
    </section><div className="mt-8 flex gap-4 border-t border-stone-200 pt-5 text-sm"><Link className="font-semibold text-emerald-800 underline" href="/privacy">Privacy Notice</Link><Link className="font-semibold text-emerald-800 underline" href="/">Back to PyLearn Pro</Link></div>
  </article></main>
}
