import Link from 'next/link'

const support = process.env.NEXT_PUBLIC_SUPPORT_EMAIL

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#faf7f0] px-4 py-10 text-stone-900"><article className="mx-auto max-w-3xl rounded-3xl border border-stone-200 bg-white p-6 shadow-sm sm:p-9"><Link href="/" className="font-bold text-emerald-800">PyLearn Pro</Link><p className="mt-5 text-xs font-bold uppercase tracking-wider text-emerald-800">Your information</p><h1 className="mt-1 text-3xl font-extrabold">Privacy Notice</h1><p className="mt-2 text-xs text-stone-500">Last updated: 8 October 2026</p>
    <section className="mt-7 space-y-5 text-sm leading-7 text-stone-700">
      <div><h2 className="font-bold text-stone-900">1. Information PyLearn Pro handles</h2><ul className="ml-5 list-disc space-y-1"><li>Account name, sign-in email, and age in years.</li><li>For learners under 18: parent or guardian name and email, plus whether they confirmed permission.</li><li>Course access, lesson progress, quick-check attempts, XP, and code a learner chooses to save or submit.</li><li>If a learner asks the optional AI tutor for help: their question, lesson title, and code included with that request.</li><li>For a manual M-Pesa request: the last four receipt characters, payer phone number, course option, amount, review status, and admin decision. PyLearn Pro does not ask for the M-Pesa PIN.</li><li>Admission guide versions, acknowledgment choices, acceptance time, and the fee snapshot shown when accepted.</li></ul></div>
      <div><h2 className="font-bold text-stone-900">2. Why it is used</h2><p>Information is used to create and secure accounts, check guardian permission, provide lessons, remember learning progress, review payment requests, send admission documents, and answer support requests. It is not used to sell learner profiles or target advertisements.</p></div>
      <div><h2 className="font-bold text-stone-900">3. Service providers</h2><p>Supabase provides account sign-in and database services. Vercel hosts the web app. When a learner chooses AI help, the submitted question and code are sent to Google Gemini. Admission and guardian emails with PDF documents are sent through Resend once email delivery is configured. These providers may process information in locations outside Kenya under their own service terms and privacy practices.</p><p className="mt-2">Google's Gemini API terms distinguish paid and unpaid usage. With unpaid services, Google may use prompts and responses to improve its products, and human reviewers may inspect them. Learners should not submit personal, sensitive, or confidential information to AI help.</p></div>
      <div><h2 className="font-bold text-stone-900">4. Children and guardian confirmation</h2><p>For a learner under 18, PyLearn Pro asks for a parent or legal guardian to review the Admission Document and confirm permission through a one-time email link before lesson access is enabled. Guardian details are used to send and record that confirmation. Kenya's Office of the Data Protection Commissioner publishes guidance on processing children's data and verifying parental or guardian consent.</p></div>
      <div><h2 className="font-bold text-stone-900">5. Copies, access, and retention</h2><p>Learners can review their saved Admission Document copies under Profile. Learning and payment records are kept with the account so the school can maintain progress and payment history. To ask about accessing, correcting, or deleting account information, contact the school support contact. The school will publish its support email and detailed retention periods before paid enrollment opens.</p></div>
      <div><h2 className="font-bold text-stone-900">6. Contact</h2><p>{support ? <>Contact <a className="font-semibold text-emerald-800 underline" href={`mailto:${support}`}>{support}</a> about a privacy question or request.</> : 'The school support email will be published here before paid enrollment opens. Until then, contact the administrator through the platform.'}</p><p className="mt-2"><a className="font-semibold text-emerald-800 underline" href="https://www.odpc.go.ke/" target="_blank" rel="noreferrer">Kenya Office of the Data Protection Commissioner</a></p></div>
    </section><div className="mt-8 flex gap-4 border-t border-stone-200 pt-5 text-sm"><Link className="font-semibold text-emerald-800 underline" href="/terms">Terms of Use</Link><Link className="font-semibold text-emerald-800 underline" href="/">Back to PyLearn Pro</Link></div>
  </article></main>
}
